# Generated by Django 3.1.3 on 2020-12-09 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0008_auto_20201209_0657'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(default='Nothing yet'),
            preserve_default=False,
        ),
    ]
