# Generated by Django 3.1.3 on 2020-12-09 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0009_category_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='NoSlugYet', max_length=30),
            preserve_default=False,
        ),
    ]
