# Generated by Django 3.1.3 on 2020-12-12 13:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forum', '0014_auto_20201211_2234'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='answer',
            name='reports',
            field=models.ManyToManyField(blank=True, null=True, related_name='reported_answers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='question',
            name='reports',
            field=models.ManyToManyField(blank=True, null=True, related_name='reported_questions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='forum.question'),
        ),
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.ManyToManyField(related_name='categories', to='forum.Category'),
        ),
        migrations.AlterField(
            model_name='question',
            name='likes',
            field=models.ManyToManyField(blank=True, null=True, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
