# Generated by Django 3.1.3 on 2020-12-14 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0016_auto_20201214_1123'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ('-date_posted',), 'verbose_name_plural': 'Categories'},
        ),
        migrations.RemoveField(
            model_name='answer',
            name='is_published',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='reports',
        ),
        migrations.RemoveField(
            model_name='question',
            name='reports',
        ),
    ]
