# Generated by Django 3.1.3 on 2020-12-05 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_delete_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answer',
            field=models.TextField(default='No Answer Yet.'),
            preserve_default=False,
        ),
    ]
