# Generated by Django 3.1.3 on 2020-12-08 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_auto_20201208_1316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='users',
        ),
    ]
